- .vscode/extensions.json
- src/App.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/common/Button.tsx
- src/components/common/Input.tsx
- src/constants/messages.ts
- src/constants/pathConst.ts
- src/interfaces/login.ts
- src/interfaces/signup.ts
- src/pages/Cart/index.tsx
- src/pages/Contact/index.tsx
- src/pages/Home/index.tsx
- src/pages/Login/index.tsx
- src/pages/NotFound/index.tsx
- src/pages/Product/index.tsx
- src/pages/Review/index.tsx
- src/pages/Search/index.tsx
- src/pages/SignIn/index.tsx
- src/pages/SignUp/index.tsx
- src/pages/Survey/index.tsx
- src/pages/User/index.tsx
- src/router.tsx
> Env: 파일트리 설정

- package-lock.json
- package.json
- swiper, paginate 설치하였습니다. npm install 해 주세요.
> Chore: swiper, paginate 설치

- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/Home/Curation.tsx
- src/components/Home/GroupTravel.tsx
- src/components/Home/SlideBanner.tsx
- src/components/Home/ThemeTravel.tsx
- src/components/Home/TravelEvent.tsx
- src/components/Home/TravelReview.tsx
- src/components/common/Button.tsx
- src/layout/Inner.tsx
- src/layout/Section.tsx
- src/pages/Home/index.tsx
- 코드 정리
- 인터페이스 이름 변경
- Home 페이지 section별 생성
> Feature: Home 페이지 section별 생성

- src/components/Home/Curation.tsx
- src/components/MyPage/WishListItem.tsx
- src/components/common/Button.tsx
- src/components/common/HeartButton.tsx
- src/components/common/Pagination.tsx
- src/components/common/ProductCard.tsx
- src/interfaces/product.ts
- src/pages/Mypage/OrderList.tsx
- src/pages/Mypage/WishList.tsx
- src/styles/GlobalStyle.tsx
- src/styles/root.ts
- onclick 타입 수정
- 하트 버튼 컴포넌트 생성
- 찜 목록 카드 생성
- 페이지네이션 컴포넌트 생성 & 적용
- background 카드 스타일 추가 및 코드 정리
- 디자인 변경에 따른 코드 정리
- 프로덕트 인터페이스 생성
- 마이페이지 찜 탭 마크업 완료
- 글로벌 스타일 추가
- 색상 추가
> Feature: 마이페이지 찜 탭 마크업 완료

- src/components/Home/Curation.tsx
- src/components/Home/GroupTravel.tsx
- src/components/common/ProductCard.tsx
> Fix: 상품 카드 이미지 영역 수정

- index.html
- src/components/MyPage/ReviewBox.tsx
- src/components/common/ProductCard.tsx
- src/pages/Mypage/MyReview.tsx
- src/styles/GlobalStyle.tsx
#30 
- 전체 폰트 변경
- 내가 쓴 리뷰 UXUI 마크업
> Feat: 내가 쓴 리뷰 UXUI 마크업

- src/components/Home/KV/KVslider.tsx
- src/components/common/Button.tsx
- src/components/common/Image.tsx
- src/components/common/SocialButtons.tsx
- src/pages/SignUp/index.tsx
- 추천인 인풋 삭제
- 소셜 연동 버튼 수정
- 슬라이드 수정 (슬라이드 텍스트 문구 추가)
- 컴포넌트 props추가
- 슬라이드 이미지 너비 수정
> Feature: 슬라이드 수정 (슬라이드 텍스트 문구 추가)

- src/components/Header.tsx
- src/components/Home/Curation.tsx
- src/components/Home/GroupTravel.tsx
- src/components/Home/KV/KVslider.tsx
- src/components/common/CheckItem.tsx
- src/components/common/Image.tsx
- src/constants/pathConst.ts
- src/pages/Login/index.tsx
- src/pages/SignUp/index.tsx
- 큐레이션 버튼 추가
- 그룹별 여행 탭 완료
- 해상도에 따른 레이아웃 무너짐 해결
- 화면 크기에 상관없이 슬라이드 이미지 꽉차게 수정
- 이미지 컴포넌트 수정
- 헤더 '찜상품' 경로 변경
- 로그인 유지 버튼 수정
> Feature: 그룹별 여행 탭 완료

- src/components/MyPage/OneOnOneCard.tsx
- src/pages/Mypage/OneOnOne.tsx
> Feat: 마이페이지 1:1문의내용 UIUX 마크업

- src/components/Header.tsx
- src/components/Theme/MonthProductList.tsx
- src/constants/pathConst.ts
- src/pages/Product/Recommend.tsx
- src/pages/Product/Theme.tsx
- src/router.tsx
#55 
- 추천 상품 페이지 마크업
- 테마별 상품 페이지 마크업
현재 슬라이드 부분 변경되지 않았습니다.
테마별 인기 여행 섹션은 메인 완성되면 연결시킬 예정입니다.
> Feat: 상품 페이지 UXUI 마크업

- src/App.tsx
- src/components/Home/Curation.tsx
- src/components/Survey/Banner.tsx
- src/pages/Survey/Result.tsx
- src/pages/Survey/index.tsx
- src/utils/scrollTop.ts
#6 
- 설문 조사 결과 페이지 마크업
- 페이지 이동 시 스크롤 상단으로 이동
> Feat: 설문조사 결과 페이지 마크업 & 페이지 이동 시 스크롤 상단으로 이동

- src/components/common/CheckItem.tsx
- src/pages/Buy/index.tsx
- CheckItem가 props로 register을 내려받지 않아도 동작하도록 수정
> Fix: CheckItem 컴포넌트 수정

- .env
- package-lock.json
- package.json
- src/api/auth.ts
- src/api/instance.ts
- src/constants/apiUrlConst.ts
- src/utils/cookie.ts
- react-cookie 라이브러리 설치
- cookies 유틸 함수 생성
- base url 변경
- api instance 생성
- api url 추가 및 키값 수정
- 회원 (회원가입, 로그인, 로그아웃, 회원정보, 회원정보 수정, 회원탈퇴) api 설정
- npm i 해주세요~
> Feature: 회원 (회원가입, 로그인, 로그아웃, 회원정보, 회원정보 수정, 회원탈퇴) api 설정

- src/api/product.ts
- src/components/common/Button.tsx
- src/components/common/Input.tsx
- src/constants/apiUrlConst.ts
- src/pages/SignUp/index.tsx
- 서버 products data 받아와 지는지 확인
- button props 추가
- 코드정리
- products api url 상수 추가
- 회원가입 기능 구현중
> Feature: 회원가입 기능 구현중

- src/api/product.ts
- src/components/Home/TravelReview.tsx
- src/components/ProductDetail/Detail.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/components/ProductDetail/TravelReview.tsx
- src/components/common/Review.tsx
- src/interfaces/product.ts
- src/interfaces/review.ts
- src/pages/Product/ProductDetail.tsx
- src/pages/Product/Theme.tsx
- src/utils/copyURL.ts
#85 
- 주소 값에 있는 상품 번호 불러와서 상세 상품 내용 나열
- 리뷰 구역 api 연결
- 상품 상단 카테고리 보여지게 수정
> Feat: 상품 상세 페이지 API 연결

- src/components/common/CheckItem.tsx
- src/components/common/Input.tsx
- src/components/common/InputItem.tsx
- src/interfaces/user.ts
- src/pages/Login/index.tsx
- src/pages/Mypage/InfoEdit.tsx
- src/pages/SignUp/index.tsx
- radio checkbox 디자인 수정
- input props 추가
- inputItem props 추가
- user interface 수정
- 비밀번호 type 수정
> Feature: 회원가입 페이지 기능 구현중

- src/components/common/CheckItem.tsx
- src/components/common/Select.tsx
- src/pages/Mypage/InfoEdit.tsx
- src/pages/SignUp/index.tsx
- src/utils/count.ts
- radio 디자인 수정
- 미사용 util 삭제
- 미사용 props 삭제
- 오타 수정
- 회원가입 취미 선택란 구현중
> Feature: 회원가입 취미 선택란 구현중

- package-lock.json
- package.json
- src/api/product.ts
- src/components/ProductPage/CategoryList.tsx
- src/components/ProductPage/ProductList.tsx
- src/components/common/Paginate.tsx
- src/components/common/SlideButtons.tsx
- src/constants/apiUrlConst.ts
- src/hooks/useSwiperSetting.ts
- src/pages/ProductsList/index.tsx
- src/styles/paginate.css
#88 
#94
- 관리자 페이지 상품 리스트 페이지네이션
- 관리자 페이지 상품 리스트 api 연결
- react-paginate 타입 설치
- 카테고리 별 페이지 상품 카드 슬라이드 custom hooks
- 카테고리 별 페이지 상품 카드 슬라이드 버튼 컴포넌트 화
react-paginate 타입 패키지 설치되었습니다 npm i 해 주세요
> Feat: 관리자 페이지 & 사용자 페이지 슬라이더

- src/api/auth.ts
- src/components/common/InputBox.tsx
- src/components/common/InputItem.tsx
- src/pages/SignUp/index.tsx
- 회원관련 api 리팩토링
- props 추가 및 적용
- 코드 정리
- 회원가입 완료
> Feature: 회원가입 완료

- src/components/Admin/UserCard.tsx
- src/components/Home/KV/KVslider.tsx
- src/components/MyPage/OneOnOneAnswerCard.tsx
- src/components/MyPage/OneOnOneCard.tsx
- src/components/MyPage/QuestionCard.tsx
- src/components/MyPage/SelectItemModal.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/components/common/CheckItem.tsx
- src/components/common/Select.tsx
- src/pages/Mypage/InfoEdit.tsx
- src/pages/PostList/index.tsx
- src/pages/Search/index.tsx
- src/styles/root.ts
- src/utils/splitDate.ts
#97 
- Select 컴포넌트 수정
- Select 컴포넌트 수정
> Feat: 마이페이지- 1:1문의 페이지 문의작성 로직 구현

- src/api/instance.ts
- src/api/product.ts
- src/components/ProductDetail/ProductInfo.tsx
- src/components/ProductDetail/TravelReview.tsx
- src/components/common/Review.tsx
- src/components/common/Select.tsx
- src/constants/apiUrlConst.ts
- src/interfaces/product.ts
- src/interfaces/review.ts
- src/pages/AddProduct/index.tsx
- src/pages/EditProduct/index.tsx
#94 
- 관리자 상품 추가 페이지 react-hook-form 설정
- 관리자 상품 수정 페이지 api 불러오기
> Feat: API 연결 및 기능 구현

- src/api/auth.ts
- src/components/MyPage/SelectItemModal.tsx
- src/components/common/CheckItem.tsx
- src/components/common/Input.tsx
- src/components/common/ModalBox.tsx
- src/constants/messages.ts
- src/interfaces/user.ts
- src/pages/Login/index.tsx
- src/pages/SignUp/index.tsx
- src/reduxStore/modalSlice.ts
- 코드 수정
- props 추가
- 모달창 디자인 수정
- 메세지 상수 추가
- 로그인 인터페이스 추가
- 로그인 완료
- 회원가입 정상 완료되면 홈화면으로 이동
- 모달 route 추가
- 회원가입 데이터 에러 수정
> Feature: 로그인 완료

- src/App.tsx
- src/components/ProductDetail/CurrentProduct.tsx
- src/components/ProductDetail/RelatedProduct.tsx
- src/components/ProductDetail/TravelReview.tsx
- src/components/common/CardTypeItem.tsx
- src/interfaces/product.ts
- src/pages/Product/ProductDetail.tsx
#85 
- 상품 상세 페이지 최근 본 상품 로컬스토리지 저장
> Feat: 상품 상세 페이지 최근 본 상품 기능 구현

- src/App.tsx
- src/api/auth.ts
- src/components/Header.tsx
- src/components/common/Input.tsx
- src/components/common/InputItem.tsx
- src/components/common/ModalBox.tsx
- src/constants/apiUrlConst.ts
- src/pages/Home/index.tsx
- src/pages/Login/index.tsx
- src/pages/Mypage/InfoEdit.tsx
- src/pages/SignUp/index.tsx
- src/reduxStore/modalSlice.ts
- src/utils/cookie.ts
- 코드정리
- 페이지 title 추가
- 쿠키 props 타입 수정
- 미사용 props 삭제
- 모달창 맨 위로
- 로딩컴포넌트 추가
- 변경된 API에 맞게 인터페이스 수정 및 적용
- 쿠키를 이용한 유저동기화
- 인풋 입력할 수 있는 최대값 설정
- 인풋 입력할 수 있는 최대값 설정
- 모달창 컴포넌트 수정
- 로그아웃 api url 수정
- 회원가입 완료 후 경로 수정 및 api 데이터 값 넘기는 에러 수정
- 모달창 route prop 추가
> Feature: 쿠키를 이용한 유저동기화 진행중

- src/api/post.ts
- src/components/MyPage/OneOnOneAnswerCard.tsx
- src/components/MyPage/OneOnOneCard.tsx
- src/components/MyPage/QnASelectBtn.tsx
- src/components/MyPage/QuestionCard.tsx
- src/components/MyPage/RadioItem.tsx
- src/components/MyPage/SelectItemModal.tsx
- src/components/common/CheckItem.tsx
- src/components/common/Loading.tsx
- src/components/common/ModalBox.tsx
- src/components/common/Select.tsx
- src/constants/apiUrlConst.ts
- src/interfaces/order.ts
- src/interfaces/post.ts
- src/main.tsx
- src/pages/Buy/index.tsx
- src/pages/Mypage/OneOnOne.tsx
- src/reduxStore/api/orderApiSlice.ts
- src/reduxStore/api/qnaApiSlice.ts
- src/reduxStore/rootReducer.ts
- src/reduxStore/store.ts
- 1:1문의 페이지 api 연동
- Select 컴포넌트 분리
- reducer 등록 시, rootReducer 파일에 등록하기
> Feat: 마이페이지 -  1:1문의 페이지 api 연동

- src/api/auth.ts
- src/api/mypage.ts
- src/api/product.ts
- src/components/MyPage/CartTable.tsx
- src/components/MyPage/MenuTab.tsx
- src/components/MyPage/ReviewBox.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/components/ProductPage/CategoryList.tsx
- src/components/common/ModalBox.tsx
- src/constants/messages.ts
- src/constants/pathConst.ts
- src/hooks/useCounter.ts
- src/interfaces/product.ts
- src/interfaces/review.ts
- src/pages/Cart/index.tsx
- src/pages/Login/index.tsx
- src/pages/Mypage/Cart.tsx
- src/pages/Mypage/CheckPassword.tsx
- src/pages/Mypage/InfoEdit.tsx
- src/pages/Mypage/MyReview.tsx
- src/pages/Mypage/index.tsx
- src/pages/Product/District.tsx
- src/reduxStore/cartSlice.ts
- src/reduxStore/store.ts
- src/router.tsx
#107 
#88 
- 수량 카운터 커스텀 훅 작성
- 지역 별 카테고리 API 기능 구현
- 마이 페이지 내가 쓴 리뷰 GET 기능 구현
- 회원 정보 수정 전 비밀번호 확인 기능 구현
- 회원 탈퇴 API 연결
회원 탈퇴 API 수정된 거 재확인 필요함
> Feat: 지역별 카테고리, 마이 페이지 기능 구현

- src/components/Header.tsx
- src/pages/Login/index.tsx
- src/router.tsx
- 관리자페이지 라우터 설정
- 관리자 로그인 시, 관리자 설정버튼 활성화
- 관리자 계정 쿠키 저장
> Feature: 관리자 로그인 시, 관리자 설정버튼 활성화

- src/interfaces/user.ts
- src/pages/Mypage/index.tsx
- src/styles/paginate.css
- 마이페이지 프로필 유저권한 표시
- 유저정보 api에 맞게 인터페이스 수정
- 페이지네이션 버튼 영역 확대
> Feature: 마이페이지 프로필 유저권한 표시

- src/constants/apiUrlConst.ts
- src/interfaces/order.ts
- src/pages/Buy/index.tsx
- src/reduxStore/api/orderApiSlice.ts
- src/reduxStore/api/qnaApiSlice.ts
- src/reduxStore/const/baseQuery.ts
#112
- 구매페이지 비회원구매 api 추가
- baseQuery 공통 상수로 변경
- 리덕스 폴더 구조 [참고사이트](https://blog.rhostem.com/posts/2020-03-04-redux-toolkits)
- components, styles 폴더에는 공용 컴포넌트, 글로벌 스타일, 믹스인처럼 유틸리티 성격을 가진 모듈을 두고, 실제 기능과 관련된 소스는 모두 features 폴더 아래에 주제별로 모으는 식
> Fix: 구매페이지 비회원이 구매할 경우 로직 추가

- src/pages/Mypage/index.tsx
> Fix: 마이페이지 유저권한 쿠키로 설정

- src/api/survey.ts
- src/components/Home/Curation.tsx
- src/components/Survey/Item.tsx
- src/constants/apiUrlConst.ts
- src/constants/surveyItems.ts
- src/interfaces/survey.ts
- src/pages/AddProduct/index.tsx
- src/pages/Survey/Result.tsx
- src/pages/Survey/index.tsx
- src/reduxStore/api/cartApiSlice.ts
- src/reduxStore/api/qnaApiSlice.ts
#122
- 설문조사 페이지 api 연결 및 기능 구현
- 메인 페이지에 있는 큐레이션 버튼 flex 수정
> Feat: 설문조사 페이지 api 연결 및 기능 구현

- src/interfaces/rootReducer.ts
- src/pages/Mypage/InfoEdit.tsx
> Feature: rootReducer 인터페이스 생성

- src/components/Header.tsx
- src/pages/Search/index.tsx
- src/utils/isCurlPath.ts
> Design: 검색페이지에선 헤더 검색바 삭제

- src/components/MyPage/QnASelectBtn.tsx
- src/components/MyPage/QuestionCard.tsx
- src/components/MyPage/SelectItemModal.tsx
- src/hooks/useOnClickOutside.ts
- src/interfaces/order.ts
- src/pages/Buy/index.tsx
- src/pages/Mypage/OneOnOne.tsx
- src/reduxStore/api/orderApiSlice.ts
- src/reduxStore/features/userInfoSlice.ts
#97 
- 마이페이지 - 1:1문의페이지 문의상품 선택 모달창 api 연동
- 모달창 뒷 배경 색 줌
> Fix: 마이페이지 - 1:1문의페이지 문의상품 선택 모달창 api 연동

- src/App.tsx
- src/components/MyPage/CartTable.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/components/common/Image.tsx
- src/constants/surveyItems.ts
- src/pages/Mypage/Cart.tsx
- src/pages/Product/ProductDetail.tsx
- src/pages/Survey/Result.tsx
- src/pages/Survey/index.tsx
#122 
#107 
#85 
- 설문조사 페이지 기능 구현
- 상품 상세 페이지에서 구매하기로 이어지는 데이터 연결
- 빈 장바구니 UI 구현
> Feat: 장바구니, 설문조사 기능 구현

- src/api/auth.ts
- src/api/product.ts
- src/components/Header.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/components/common/HeartButton.tsx
- src/constants/apiUrlConst.ts
- src/interfaces/product.ts
- src/interfaces/wishlist.ts
- src/pages/Login/index.tsx
- src/pages/Mypage/WishList.tsx
- src/pages/Mypage/index.tsx
- src/pages/Product/ProductDetail.tsx
- src/pages/ProductsList/index.tsx
- src/reduxStore/store.ts
#94 
#85 
#107 
- 상품 상세 페이지에서 판매 중인 상품이 아니면 고를 수 없게 하기
- 찜 하기 기능 붙이는 중
- 관리자 페이지 전체 상품 수
- 유저 정보 헤더에서 계속 불러서 오기
- 회원 탈퇴
- 마이 페이지 useSelector로 정보 불러오기
> Feat: 상품 상세 페이지 & 관리자 페이지

- src/components/Home/Banner.tsx
- src/pages/Home/index.tsx
- src/pages/Search/index.tsx
> Fix: 배포 오류 해결

- src/interfaces/product.ts
- src/pages/ProductsList/index.tsx
- src/reduxStore/api/adminProductApiSlice.ts
- src/reduxStore/rootReducer.ts
- src/reduxStore/store.ts
> Feat: 관리자 페이지 상품 삭제 기능 구현

- src/interfaces/transaction.ts
- src/pages/Admin/TransactionList.tsx
- 거래내역 인터페이스 수정
- 관리자 거래내역 진행중
> Feature: 관리자 거래내역 진행중

- src/components/Header.tsx
- src/components/Home/TravelReview.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/constants/pathConst.ts
- src/pages/Contact/index.tsx
- src/pages/Review/index.tsx
- src/pages/User/index.tsx
- src/routes/router.tsx
#149 
- 헤더 커뮤니티 변경
- 프라이빗 라우터 설정
> Feat: 헤더 및 프라이빗 라우터 설정

- src/components/ProductPage/MonthProductList.tsx
- src/components/ProductPage/ProductList.tsx
- src/components/common/Review.tsx
- src/constants/messages.ts
- src/pages/Mypage/OneOnOne.tsx
- src/pages/Mypage/OrderList.tsx
- src/pages/Mypage/WishList.tsx
- src/pages/ProductsList/index.tsx
- src/routes/AdminRoute.tsx
- src/routes/router.tsx
#107
#149 
- 찜 하기 기능 구현 (상품 리스트에서 실시간 반영 안 됨)
- 마이 페이지 내역 없을 시 화면 처리
- 접근 권한 설정
> Feat: 찜하기 기능, 에러 처리 정리

- src/components/MyPage/OrderDetailCard.tsx
- src/components/MyPage/ReviewBox.tsx
- src/components/MyPage/ReviewModal.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/components/common/ReviewModal.tsx
- src/interfaces/review.ts
- src/pages/Buy/index.tsx
- src/reduxStore/api/reviewApiSlice.ts
- src/routes/router.tsx
fix #{issueNumber} (~ed, ~es)
resolve #
close #
- 리뷰 모달창 기능 구현
-
-
> Feat: 리뷰 모달창 기능 구현

- src/components/Home/ChatBot.tsx
- src/components/Home/Curation.tsx
- src/components/Home/FloatingNav.tsx
- src/components/Home/TravelReview.tsx
- src/components/MyPage/ReviewBox.tsx
- src/components/ProductDetail/TravelReview.tsx
- src/components/common/Review.tsx
- src/components/common/StarRateWrapGet.tsx
- src/interfaces/review.ts
- src/pages/Mypage/MyReview.tsx
- src/pages/Survey/Result.tsx
> Fix: 별점리스트 수정

- src/components/Home/ChatBot.tsx
- src/components/MyPage/OneOnOneCard.tsx
- src/components/MyPage/OrderDetailCard.tsx
- src/components/MyPage/ReviewBox.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/components/ProductDetail/TravelReview.tsx
- src/components/common/CardTypeItem.tsx
- src/components/common/StarRateWrapGet.tsx
- src/pages/Consult/index.tsx
fix #{issueNumber} (~ed, ~es)
resolve #
close #
- 각 컴포넌트들 수정
-
-
> Fix: 상세페이지 및 모달창 수정

- src/routes/AdminRoute.tsx
- src/routes/router.tsx
> Refactor: 관리자 페이지 라우터 수정

- src/components/Header.tsx
- src/components/Home/Curation.tsx
- src/components/Home/CurationSelectBtn.tsx
- src/components/Home/KV/KVslider.tsx
- src/components/Home/mobile/MCuration.tsx
- src/components/Home/mobile/MProductCard.tsx
- src/components/Home/mobile/MSlideBanner.tsx
- src/components/common/ProductCard.tsx
- src/pages/Home/index.tsx
fix #{issueNumber} (~ed, ~es)
resolve #
close #
- 메인페이지 - KV슬라이드 및 큐레이션 영역 모바일 마크업
- 아이폰12기준으로 작업 진행중
> Feat: 메인페이지 - KV슬라이드 및 큐레이션 영역 모바일 마크업

- src/components/Header.tsx
- src/interfaces/user.ts
- src/pages/Mypage/InfoEdit.tsx
- src/pages/SignUp/index.tsx
- src/pages/Survey/Result.tsx
- src/reduxStore/api/userApiSlice.ts
#168 
- 마이 페이지 회원 정보 수정 api 변경
- 마이 페이지 회원 탈퇴 api 수정
- 로그아웃 기능 removeCookie 수정
- 회원가입 api 수정
- 설문조사 회원 정보 api 수정
> Refactor: 로그인 api rtk-query로 수정

- src/App.tsx
- src/components/Home/mobile/MCuration.tsx
- src/components/Home/mobile/MProductCard.tsx
- src/components/Home/mobile/MTravelReview.tsx
- src/components/Mobile/MFloating.tsx
- src/components/Mobile/MFooter.tsx
- src/pages/Home/index.tsx
fix #{issueNumber} (~ed, ~es)
resolve #
close #
- Swiper에 absolute 주면 드래그 안되는 현상 해결
> Fix: 메인페이지 큐레이션 영역 모바일 버전 수정

- src/components/Home/GroupTravel.tsx
- src/components/Home/ThemeTravel.tsx
- src/components/ProductDetail/CurrentProduct.tsx
- src/components/ProductDetail/ProductInfo.tsx
- src/components/ProductDetail/RelatedProduct.tsx
- src/components/ProductDetail/TravelReview.tsx
- src/components/ProductPage/CategoryList.tsx
- src/components/ProductPage/MonthProductList.tsx
- src/components/ProductPage/ProductList.tsx
- src/hooks/useSwiperSetting.ts
- src/pages/Product/Group.tsx
- src/pages/Product/ProductDetail.tsx
- src/reduxStore/api/productsApiSlice.ts
- src/reduxStore/api/wishlistApislice.ts
- src/reduxStore/rootReducer.ts
- src/reduxStore/store.ts
#147 
- 찜 기능 rtk-query 테스트
- 상품 불러오기 rtk-query로 변경
api는 잘 작동하나 화면에서 하트가 실시간으로 변경되지 않아 테스트 중입니다
> Test: 찜 기능 rtk-query 테스트 중

- src/components/Home/mobile/MTravelReview.tsx
- src/components/common/Review.tsx
#174 
- 메인 페이지 - 리뷰영역 모바일 페이지 구현
> Fix: 메인 페이지 - 리뷰영역 모바일 페이지 구현

- src/components/Home/mobile/MTravelReview.tsx
- src/components/common/Review.tsx
- 실수로 merge눌러서 revert함 (merge 할때 문제는 없었음)
> Revert "Fix: 메인 페이지 - 리뷰영역 모바일 페이지 구현"
